name: Publish Documentation to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - run: pip install mkdocs==1.6.1 mkdocs-material==9.6.15 mkdocstrings==0.29.1 mkdocstrings-python==1.16.12
      - run: mkdocs gh-deploy --force